### ISSUE TITLE
Please take this down.

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Ghost0159/Ghost-Eshop-Alternative-3ds#2]
Universal-Updater's purpose is not for Piracy things. Universal-Updater's purpose was for allowing to easy update Homebrew apps.

I do suggest to take this down as fast as possible. Thanks. ~StackZ from Universal-Team.

**Comment by Ghost0159** [comment]
I have not deleted my freeshop, because there is no way to download
games from your consoles,
but I agree that you give me a homebrew with my name allowing to
easily implement my freeshop, because I do not know anything about
programming.
More than risk for a script that you did not create.
Thank you for your responses.
Do I have the right to modify Universal-Updater, to put a new name, my
nickname as author is to put my script with.
My email: contact.ghost01@gmail.com
My github: https://github.com/ghost0159

**Comment by Ghost0159** [comment]
I am thinking with other developer is former developer whose name I will not locate for the moment see ever if he wishes, has a homebrew using this script is so that this script is not accessible for Universal-Updater, as well as no affiliation with Universal-Team.
In the meantime, I take all responsibility for this script and will continue to improve it.
Thanks for Universal-Updater, continued like this, I swear to find a solution within 2 weeks or even 1 month.
Regards Ghost0159
